### ISSUE TITLE
HTTPD >= 2.2 error mod pagespeed

### ISSUE THREAD

**Issue by LDJuice** [apache/incubator-pagespeed-mod#1518]
I'm getting the following error below when trying to install mod_pagespeed. I was trying to build it from source but as the errors show below this didnt work out. Is there anyone who knows what I have to do? Apache is on 2.4. Thanks in advance!

[root@mgvps mod_pagespeed]# gclient sync --force --jobs=1
Running depot tools as root is sad.
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-chec                                                                                        kout" "--progress" "https://chromium.googlesource.com/chromium/src/testing" "/ro                                                                                        ot/mod_pagespeed/src/_gclient_testing_xtMOZm"' in /root/mod_pagespeed failed; wi                                                                                        ll retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-chec                                                                                        kout" "--progress" "https://chromium.googlesource.com/chromium/src/testing" "/ro                                                                                        ot/mod_pagespeed/src/_gclient_testing_xtMOZm"' in /root/mod_pagespeed failed; wi                                                                                        ll retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-chec                                                                                        kout" "--progress" "https://chromium.googlesource.com/chromium/src/testing" "/ro                                                                                        ot/mod_pagespeed/src/_gclient_testing_xtMOZm"' in /root/mod_pagespeed failed; wi                                                                                        ll retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-chec                                                                                        kout" "--progress" "https://chromium.googlesource.com/chromium/src/testing" "/ro                                                                                        ot/mod_pagespeed/src/_gclient_testing_xtMOZm"' in /root/mod_pagespeed failed; wi                                                                                        ll retry after a short nap...

src/testing (ERROR)
----------------------------------------
[0:00:00] Started.
[0:00:00]

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progr                                                                                        ess https://chromium.googlesource.com/chromium/src/testing /root/mod_pagespeed/s                                                                                        rc/_gclient_testing_xtMOZm' in '/root/mod_pagespeed'
[0:00:00] Unknown option: -c
[0:00:00] usage: git [--version] [--exec-path[=GIT_EXEC_PATH]] [--html-path]
[0:00:00]            [-p|--paginate|--no-pager] [--no-replace-objects]
[0:00:00]            [--bare] [--git-dir=GIT_DIR] [--work-tree=GIT_WORK_TREE]
[0:00:00]            [--help] COMMAND [ARGS]

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progr                                                                                        ess https://chromium.googlesource.com/chromium/src/testing /root/mod_pagespeed/s                                                                                        rc/_gclient_testing_xtMOZm' in '/root/mod_pagespeed'
[0:00:00] Unknown option: -c
[0:00:00] usage: git [--version] [--exec-path[=GIT_EXEC_PATH]] [--html-path]
[0:00:00]            [-p|--paginate|--no-pager] [--no-replace-objects]
[0:00:00]            [--bare] [--git-dir=GIT_DIR] [--work-tree=GIT_WORK_TREE]
[0:00:00]            [--help] COMMAND [ARGS]

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progr                                                                                        ess https://chromium.googlesource.com/chromium/src/testing /root/mod_pagespeed/s                                                                                        rc/_gclient_testing_xtMOZm' in '/root/mod_pagespeed'
[0:00:01] Unknown option: -c
[0:00:01] usage: git [--version] [--exec-path[=GIT_EXEC_PATH]] [--html-path]
[0:00:01]            [-p|--paginate|--no-pager] [--no-replace-objects]
[0:00:01]            [--bare] [--git-dir=GIT_DIR] [--work-tree=GIT_WORK_TREE]
[0:00:01]            [--help] COMMAND [ARGS]

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progr                                                                                        ess https://chromium.googlesource.com/chromium/src/testing /root/mod_pagespeed/s                                                                                        rc/_gclient_testing_xtMOZm' in '/root/mod_pagespeed'
[0:00:03] Unknown option: -c
[0:00:03] usage: git [--version] [--exec-path[=GIT_EXEC_PATH]] [--html-path]
[0:00:03]            [-p|--paginate|--no-pager] [--no-replace-objects]
[0:00:03]            [--bare] [--git-dir=GIT_DIR] [--work-tree=GIT_WORK_TREE]
[0:00:03]            [--help] COMMAND [ARGS]
Traceback (most recent call last):
  File "/root/bin/depot_tools/gclient_scm.py", line 908, in _Clone
    self._Run(clone_cmd, options, cwd=self._root_dir, retry=True)
  File "/root/bin/depot_tools/gclient_scm.py", line 1197, in _Run
    gclient_utils.CheckCallAndFilterAndHeader(cmd, env=env, **kwargs)
  File "/root/bin/depot_tools/gclient_utils.py", line 303, in CheckCallAndFilter                                                                                        AndHeader
    return CheckCallAndFilter(args, **kwargs)
  File "/root/bin/depot_tools/gclient_utils.py", line 549, in CheckCallAndFilter
    rv, args, kwargs.get('cwd', None), None, None)
  File "/root/bin/depot_tools/subprocess2.py", line 37, in __init__
    super(CalledProcessError, self).__init__(returncode, cmd, output=stdout)
TypeError: __init__() got an unexpected keyword argument 'output'
----------------------------------------
Traceback (most recent call last):
  File "/root/bin/depot_tools/gclient.py", line 2129, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/root/bin/depot_tools/gclient.py", line 2115, in main
    return dispatcher.execute(OptionParser(), argv)
  File "/root/bin/depot_tools/subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "/root/bin/depot_tools/gclient.py", line 1877, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "/root/bin/depot_tools/gclient.py", line 1364, in RunOnDeps
    work_queue.flush(revision_overrides, command, args, options=self._options)
  File "/root/bin/depot_tools/gclient_utils.py", line 920, in flush
    self._run_one_task(self.queued.pop(i), args, kwargs)
  File "/root/bin/depot_tools/gclient_utils.py", line 1012, in _run_one_task
    task_item.run(*args, **kwargs)
  File "/root/bin/depot_tools/gclient.py", line 773, in run
    file_list)
  File "/root/bin/depot_tools/gclient_scm.py", line 156, in RunCommand
    return getattr(self, command)(options, args, file_list)
  File "/root/bin/depot_tools/gclient_scm.py", line 438, in update
    self._Clone(revision, url, options)
  File "/root/bin/depot_tools/gclient_scm.py", line 908, in _Clone
    self._Run(clone_cmd, options, cwd=self._root_dir, retry=True)
  File "/root/bin/depot_tools/gclient_scm.py", line 1197, in _Run
    gclient_utils.CheckCallAndFilterAndHeader(cmd, env=env, **kwargs)
  File "/root/bin/depot_tools/gclient_utils.py", line 303, in CheckCallAndFilter                                                                                        AndHeader
    return CheckCallAndFilter(args, **kwargs)
  File "/root/bin/depot_tools/gclient_utils.py", line 549, in CheckCallAndFilter
    rv, args, kwargs.get('cwd', None), None, None)
  File "/root/bin/depot_tools/subprocess2.py", line 37, in __init__
    super(CalledProcessError, self).__init__(returncode, cmd, output=stdout)
TypeError: __init__() got an unexpected keyword argument 'output'

**Comment by morlovich** [comment]
Looks like your git executable is too old to have a -c option?

**Comment by LDJuice** [comment]
Thanks for your reply! I updated the git version to the most recent one and I followed the instructions from the link below. Now I'm getting the error which I copy paste below the link. Any idea how I can solve this?

https://modpagespeed.com/doc/build_mod_pagespeed_from_source

[root@mgvps mod_pagespeed]# gclient sync --force --jobs=1
Running depot tools as root is sad.
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--pr            ogress" "git://git.apache.org/apr.git" "/root/mod_pagespeed/src/third_party/apr/_gclient_sr            c_zrNq7n"' in /root/mod_pagespeed failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--pr            ogress" "git://git.apache.org/apr.git" "/root/mod_pagespeed/src/third_party/apr/_gclient_sr            c_zrNq7n"' in /root/mod_pagespeed failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "git://git.apache.org/apr.git" "/root/mod_pagespeed/src/third_party/apr/_gclient_src_zrNq7n"' in /root/mod_pagespeed failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "git://git.apache.org/apr.git" "/root/mod_pagespeed/src/third_party/apr/_gclient_src_zrNq7n"' in /root/mod_pagespeed failed; will retry after a short nap...

src/third_party/apr/src (ERROR)
----------------------------------------
[0:00:02] Started.
[0:00:02]

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress git://git.apache.org/apr.git /root/mod_pagespeed/src/third_party/apr/_gclient_src_zrNq7n' in '/root/mod_pagespeed'
[0:00:02] Cloning into '/root/mod_pagespeed/src/third_party/apr/_gclient_src_zrNq7n'...
[0:01:05] fatal: unable to connect to git.apache.org:
[0:01:05] git.apache.org[0: 54.84.58.65]: errno=Connection timed out
[0:01:05]

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress git://git.apache.org/apr.git /root/mod_pagespeed/src/third_party/apr/_gclient_src_zrNq7n' in '/root/mod_pagespeed'
[0:01:05] Cloning into '/root/mod_pagespeed/src/third_party/apr/_gclient_src_zrNq7n'...
[0:02:08] fatal: unable to connect to git.apache.org:
[0:02:08] git.apache.org[0: 54.84.58.65]: errno=Connection timed out
[0:02:08]

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress git://git.apache.org/apr.git /root/mod_pagespeed/src/third_party/apr/_gclient_src_zrNq7n' in '/root/mod_pagespeed'
[0:02:09] Cloning into '/root/mod_pagespeed/src/third_party/apr/_gclient_src_zrNq7n'...
[0:03:12] fatal: unable to connect to git.apache.org:
[0:03:12] git.apache.org[0: 54.84.58.65]: errno=Connection timed out
[0:03:12]

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress git://git.apache.org/apr.git /root/mod_pagespeed/src/third_party/apr/_gclient_src_zrNq7n' in '/root/mod_pagespeed'
[0:03:14] Cloning into '/root/mod_pagespeed/src/third_party/apr/_gclient_src_zrNq7n'...
[0:04:17] fatal: unable to connect to git.apache.org:
[0:04:17] git.apache.org[0: 54.84.58.65]: errno=Connection timed out
[0:04:17]
Traceback (most recent call last):
  File "/root/bin/depot_tools/gclient_scm.py", line 908, in _Clone
    self._Run(clone_cmd, options, cwd=self._root_dir, retry=True)
  File "/root/bin/depot_tools/gclient_scm.py", line 1197, in _Run
    gclient_utils.CheckCallAndFilterAndHeader(cmd, env=env, **kwargs)
  File "/root/bin/depot_tools/gclient_utils.py", line 303, in CheckCallAndFilterAndHeader
    return CheckCallAndFilter(args, **kwargs)
  File "/root/bin/depot_tools/gclient_utils.py", line 549, in CheckCallAndFilter
    rv, args, kwargs.get('cwd', None), None, None)
  File "/root/bin/depot_tools/subprocess2.py", line 37, in __init__
    super(CalledProcessError, self).__init__(returncode, cmd, output=stdout)
TypeError: __init__() got an unexpected keyword argument 'output'
----------------------------------------
Traceback (most recent call last):
  File "/root/bin/depot_tools/gclient.py", line 2129, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/root/bin/depot_tools/gclient.py", line 2115, in main
    return dispatcher.execute(OptionParser(), argv)
  File "/root/bin/depot_tools/subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "/root/bin/depot_tools/gclient.py", line 1877, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "/root/bin/depot_tools/gclient.py", line 1364, in RunOnDeps
    work_queue.flush(revision_overrides, command, args, options=self._options)
  File "/root/bin/depot_tools/gclient_utils.py", line 920, in flush
    self._run_one_task(self.queued.pop(i), args, kwargs)
  File "/root/bin/depot_tools/gclient_utils.py", line 1012, in _run_one_task
    task_item.run(*args, **kwargs)
  File "/root/bin/depot_tools/gclient.py", line 773, in run
    file_list)
  File "/root/bin/depot_tools/gclient_scm.py", line 156, in RunCommand
    return getattr(self, command)(options, args, file_list)
  File "/root/bin/depot_tools/gclient_scm.py", line 438, in update
    self._Clone(revision, url, options)
  File "/root/bin/depot_tools/gclient_scm.py", line 916, in _Clone
    if os.listdir(tmp_dir):
OSError: [Errno 2] No such file or directory: '/root/mod_pagespeed/src/third_party/apr/_gclient_src_zrNq7n'

**Comment by oschaaf** [comment]
@LDJuice It may be worth retrying, a lot of the error lines look like they may have been caused by transient (network) problems
